export const PLATFORM_OWNER_ID = "platform";
export const DRIVER_POOL_OWNER_ID = "driver_pool";

export const DEFAULT_COMMISSION_RATE = 0.2; // 20% commission on food items
export const DEFAULT_MAINTENANCE_FEE = 150000; // VND, configurable per restaurant
export const DEFAULT_MAINTENANCE_INTERVAL_DAYS = 30;

export const WALLET_TYPES = {
    PLATFORM_MAIN: "platform_main",
    RESTAURANT_LIABILITY: "restaurant_liability",
    DRIVER_LIABILITY: "driver_liability",
    PLATFORM_REVENUE: "platform_revenue"
};

export const LEDGER_ENTRY_TYPES = {
    ONLINE_ITEM_CAPTURE: "ORDER_ONLINE_CAPTURE_ITEMS",
    ONLINE_SHIPPING_CAPTURE: "ORDER_ONLINE_CAPTURE_SHIPPING",
    ONLINE_SHIPPING_RESTAURANT_SHARE: "ORDER_ONLINE_SHIPPING_RESTAURANT_SHARE",
    ONLINE_COMMISSION: "ORDER_ONLINE_COMMISSION",
    MAINTENANCE_FEE: "ORDER_MAINTENANCE_FEE",
    COD_COMMISSION: "ORDER_COD_COMMISSION",
    COD_MAINTENANCE: "ORDER_COD_MAINTENANCE",
    RESTAURANT_PAYOUT: "RESTAURANT_PAYOUT",
    COD_SETTLEMENT_INVOICE: "COD_SETTLEMENT_INVOICE"
};

export const FUND_SOURCES = {
    ONLINE: "online",
    COD: "cod"
};

export const SHIPPING_SHARES = {
    RESTAURANT: 0.1,
    DRIVER: 0.9
};
